//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXC_RECUPERACION
    {
        public int REC_Recuperacion { get; set; }
        public Nullable<int> PRP_ProyeccionPago { get; set; }
        public Nullable<int> FRM_FormaPago { get; set; }
        public Nullable<System.DateTime> REC_FechaRecuperacion { get; set; }
        public Nullable<decimal> REC_MontoRecuperado { get; set; }
        public Nullable<decimal> REC_Recargos { get; set; }
        public Nullable<int> TTR_TipoTransaccion { get; set; }
    
        public virtual CXC_FORMAPAGO CXC_FORMAPAGO { get; set; }
        public virtual CXC_PROYECCIONPAGO CXC_PROYECCIONPAGO { get; set; }
        public virtual CXC_TIPOTRANSACCION CXC_TIPOTRANSACCION { get; set; }
    }
}
