//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXC_FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CXC_FACTURA()
        {
            this.CXC_CREDITO = new HashSet<CXC_CREDITO>();
            this.CXC_DETALLEFACTURA = new HashSet<CXC_DETALLEFACTURA>();
        }
    
        public int FAC_Factura { get; set; }
        public string FAC_Serie { get; set; }
        public string FAC_Numero { get; set; }
        public Nullable<System.DateTime> FAC_Fecha { get; set; }
        public Nullable<decimal> FAC_TOTAL { get; set; }
        public string FAC_Certificado { get; set; }
        public string FAC_FirmaElectronica { get; set; }
        public Nullable<int> EMP_Empresa { get; set; }
        public Nullable<int> CLI_Cliente { get; set; }
        public Nullable<int> TPA_TipoPago { get; set; }
    
        public virtual CXC_CLIENTE CXC_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CXC_CREDITO> CXC_CREDITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CXC_DETALLEFACTURA> CXC_DETALLEFACTURA { get; set; }
        public virtual CXC_EMPRESA CXC_EMPRESA { get; set; }
        public virtual CXC_TIPOPAGO CXC_TIPOPAGO { get; set; }
    }
}
