//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXC_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CXC_PRODUCTO()
        {
            this.CXC_DETALLEFACTURA = new HashSet<CXC_DETALLEFACTURA>();
        }
    
        public int PRD_Producto { get; set; }
        public string PRD_Marca { get; set; }
        public string PRD_Modelo { get; set; }
        public Nullable<int> PRD_Anio { get; set; }
        public string PRD_Tipo { get; set; }
        public string PRD_Estado { get; set; }
        public Nullable<int> PRD_Existencia { get; set; }
        public Nullable<int> PRD_Costo { get; set; }
        public Nullable<int> PRD_PrecioVenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CXC_DETALLEFACTURA> CXC_DETALLEFACTURA { get; set; }
    }
}
