//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXC_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CXC_CLIENTE()
        {
            this.CXC_FACTURA = new HashSet<CXC_FACTURA>();
        }
    
        public int CLI_Cliente { get; set; }
        public Nullable<int> TPP_TipoPersona { get; set; }
        public Nullable<int> PER_Persona { get; set; }
        public Nullable<int> RRH_Empleado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CXC_FACTURA> CXC_FACTURA { get; set; }
        public virtual RRH_EMPLEADO RRH_EMPLEADO1 { get; set; }
        public virtual CXC_PERSONA CXC_PERSONA { get; set; }
        public virtual CXC_TIPO_PERSONA CXC_TIPO_PERSONA { get; set; }
    }
}
