//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXC_CREDITO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CXC_CREDITO()
        {
            this.CXC_PROYECCIONPAGO = new HashSet<CXC_PROYECCIONPAGO>();
        }
    
        public int CRE_Credito { get; set; }
        public Nullable<int> FAC_Factura { get; set; }
        public Nullable<int> DCR_DiasCredito { get; set; }
        public Nullable<System.DateTime> CRE_FechaCredito { get; set; }
        public Nullable<decimal> CRE_MontoCredito { get; set; }
        public Nullable<decimal> CRE_MontoPagado { get; set; }
        public Nullable<decimal> CRE_Recargos { get; set; }
        public Nullable<int> EST_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CXC_PROYECCIONPAGO> CXC_PROYECCIONPAGO { get; set; }
        public virtual CXC_DIASCREDITO CXC_DIASCREDITO { get; set; }
        public virtual CXC_FACTURA CXC_FACTURA { get; set; }
    }
}
