//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Logica.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CxCEntities1 : DbContext
    {
        public CxCEntities1()
            : base("name=CxCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CXC_CLIENTE> CXC_CLIENTE { get; set; }
        public virtual DbSet<CXC_CREDITO> CXC_CREDITO { get; set; }
        public virtual DbSet<CXC_DETALLEFACTURA> CXC_DETALLEFACTURA { get; set; }
        public virtual DbSet<CXC_DIASCREDITO> CXC_DIASCREDITO { get; set; }
        public virtual DbSet<CXC_EMPRESA> CXC_EMPRESA { get; set; }
        public virtual DbSet<CXC_ESTADOCREDITO> CXC_ESTADOCREDITO { get; set; }
        public virtual DbSet<CXC_FACTURA> CXC_FACTURA { get; set; }
        public virtual DbSet<CXC_FORMAPAGO> CXC_FORMAPAGO { get; set; }
        public virtual DbSet<CXC_PERSONA> CXC_PERSONA { get; set; }
        public virtual DbSet<CXC_PRODUCTO> CXC_PRODUCTO { get; set; }
        public virtual DbSet<CXC_PROYECCIONPAGO> CXC_PROYECCIONPAGO { get; set; }
        public virtual DbSet<CXC_RECUPERACION> CXC_RECUPERACION { get; set; }
        public virtual DbSet<CXC_TIPO_PERSONA> CXC_TIPO_PERSONA { get; set; }
        public virtual DbSet<CXC_TIPOPAGO> CXC_TIPOPAGO { get; set; }
        public virtual DbSet<CXC_TIPOTRANSACCION> CXC_TIPOTRANSACCION { get; set; }
        public virtual DbSet<RRH_EMPLEADO> RRH_EMPLEADO { get; set; }
        public virtual DbSet<RRH_PUESTO> RRH_PUESTO { get; set; }
        public virtual DbSet<SEG_ROL> SEG_ROL { get; set; }
        public virtual DbSet<SEG_USUARIO> SEG_USUARIO { get; set; }
    
        public virtual ObjectResult<SP_RPT_CLIENTES_X_REGION_Result> SP_RPT_CLIENTES_X_REGION(string vTipPago)
        {
            var vTipPagoParameter = vTipPago != null ?
                new ObjectParameter("vTipPago", vTipPago) :
                new ObjectParameter("vTipPago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RPT_CLIENTES_X_REGION_Result>("SP_RPT_CLIENTES_X_REGION", vTipPagoParameter);
        }
    
        public virtual ObjectResult<SP_RPT_Facturacion_x_Fecha_TipoPago_Result> SP_RPT_Facturacion_x_Fecha_TipoPago(string vTipPago)
        {
            var vTipPagoParameter = vTipPago != null ?
                new ObjectParameter("vTipPago", vTipPago) :
                new ObjectParameter("vTipPago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RPT_Facturacion_x_Fecha_TipoPago_Result>("SP_RPT_Facturacion_x_Fecha_TipoPago", vTipPagoParameter);
        }
    
        public virtual ObjectResult<spConsulta_Result> spConsulta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsulta_Result>("spConsulta");
        }
    
        public virtual ObjectResult<spConsultaUno_Result> spConsultaUno(string iDNIT)
        {
            var iDNITParameter = iDNIT != null ?
                new ObjectParameter("IDNIT", iDNIT) :
                new ObjectParameter("IDNIT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaUno_Result>("spConsultaUno", iDNITParameter);
        }
    }
}
