//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Logica.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClientesEntities : DbContext
    {
        public ClientesEntities()
            : base("name=ClientesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PER_PERSONA> PER_PERSONA { get; set; }
    
       /* public virtual ObjectResult<spDatosPrincipales_Result> spDatosPrincipales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDatosPrincipales_Result>("spDatosPrincipales");
        }*/
    
        public virtual ObjectResult<spConsulta_Result> spConsulta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsulta_Result>("spConsulta");
        }
    
        public virtual ObjectResult<spConsultaUno_Result> spConsultaUno(string iDNIT)
        {
            var iDNITParameter = iDNIT != null ?
                new ObjectParameter("IDNIT", iDNIT) :
                new ObjectParameter("IDNIT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaUno_Result>("spConsultaUno", iDNITParameter);
        }
    }
}
