//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_PERSONA
    {
        public int PER_Persona1 { get; set; }
        public string PER_PrimerNombre { get; set; }
        public string PER_SegundoNombre { get; set; }
        public string PER_PrimerApellido { get; set; }
        public string PER_SegundoApellido { get; set; }
        public string PER_Identificacion { get; set; }
        public Nullable<System.DateTime> PER_FechaNacimiento { get; set; }
        public string PER_Telefono { get; set; }
        public string PER_Departamento { get; set; }
        public string PER_Municipio { get; set; }
        public string PER_Direccion { get; set; }
        public string PER_NIT { get; set; }
    }
}
